Use edl freebase mapping to get qnodes
joecummings/cdse-covid pull request #104
Opened 2021-12-10 20:33 UTC by elizlee

Closes #96 
Helps a lot with #98

2021-12-15 13:49 UTC, joecummings commented on cdse_covid/semantic_extraction/run_entity_merging.py
> +from typing import Dict, MutableMapping, Optional, Tuple
You should be able to use `MutableMapping` in place of `Dict`. One less import.

2021-12-15 14:03 UTC, joecummings commented on cdse_covid/pegasus_pipeline/ingesters/edl_output_ingester.py
> +    with open(edl_output / "merged.cs", "r", encoding="utf-8") as handle2:
Can L65-67 be removed and the rest be moved up? Is there a reason why this can't be accomplished in the same loop?

2021-12-15 14:04 UTC, joecummings requested changes
Few comments. Also, can you add a piece about this in the README, specifically referencing what we mean by the Freebase Qnode file and maybe even upload a link to it?

2021-12-15 16:10 UTC, elizlee commented on cdse_covid/pegasus_pipeline/ingesters/edl_output_ingester.py
> +    with open(edl_output / "merged.cs", "r", encoding="utf-8") as handle2:
This second loop handles mentions and looks up data in `all_entities`, which is created through the first loop. The mentions are listed before the lines with freebase links, so if they were in the same loop, there's a chance that its freebase link wouldn't be found.

2021-12-16 17:52 UTC, joecummings approved these changes
LGTM!

2021-12-16 17:53 UTC, merged