Use amr to find x variable
joecummings/cdse-covid pull request #18
Opened 2021-10-27 21:37 UTC by elizlee

* Finds X-variables during the AMR-parsing step
* Makes use of alignments to pull argument text (including claimers) from the source sentence
* Adds new module for AMR/x-variable methods
Closes #19

2021-11-02 18:39 UTC, joecummings commented on cdse_covid/semantic_extraction/claimer_utils.py
> +        return []
I'm not sure why you're returning a `List`. Are you allowing for potentially more than one claimer?

2021-11-02 18:40 UTC, joecummings commented on cdse_covid/semantic_extraction/claimer_utils.py
>                          claimers.add(f"'{name}'")
This sequence occurs here and on line 100 so it can be refactored into its own function.

2021-11-02 18:41 UTC, joecummings commented on cdse_covid/semantic_extraction/claimer_utils.py
> +    print("Printing info in x-variable method...")
Can you either remove these or change them to `logging` statements if you want to keep them in?

2021-11-02 18:42 UTC, joecummings commented on cdse_covid/semantic_extraction/claimer_utils.py
> +    print("Printing info in x-variable method...")
Same with all print statements in these files. I spotted a few others.

2021-11-02 18:43 UTC, joecummings commented on cdse_covid/semantic_extraction/claimer_utils.py
> +    if any(f"{place_term}-X" in claim_template for place_term in place_variables):
How did you come up with all the rules from here to L207? It looks like only a few templates and entity types are targeted. 

I assume you have a good reason for this, but it would be helpful to drop in a comment giving a brief explanation.

2021-11-02 18:46 UTC, joecummings requested changes
Few comments and can you also rebase against master? That should get rid of that `merge` commit hopefully.

2021-11-02 20:38 UTC, joecummings commented on cdse_covid/semantic_extraction/run_srl.py
> +    if claims_with_missing_x_variables:
We still want to get the Event Semantics from SRL - only the X variable finding should be skipped if the claim has a missing x variable.

2021-11-02 20:40 UTC, joecummings commented on cdse_covid/semantic_extraction/amr_extraction_utils.py
> +            raise RuntimeError(
Can you print out either the trace or the bad value?

2021-11-02 20:41 UTC, elizlee commented on cdse_covid/semantic_extraction/run_srl.py
> +    if claims_with_missing_x_variables:
Ohh, got it

2021-11-02 20:51 UTC, joecummings commented on cdse_covid/semantic_extraction/amr_extraction_utils.py
> +def identify_x_variable(amr: AMR, alignments: List[AMR_Alignment], claim_template: str) -> Optional[str]:
All of these rules are really great, because they are going to improve our recall immensely. That said, they are fairly handcrafted towards the templates provided for the COVID-19 domain. 

It's a program goal to have this system be able to operate over other potential topics. Would it be possible to keep this function as is, but create an alternate `identify_x_variable_generic` that has less assumptions? For example, using SpaCy's entity recognition to tell if there is a `FAC/GPE/LOC`, then applying the correct rule. Or if the sentiment/outcome is negative. 

Does that make sense?

2021-11-02 21:20 UTC, elizlee commented on cdse_covid/semantic_extraction/amr_extraction_utils.py
> +def identify_x_variable(amr: AMR, alignments: List[AMR_Alignment], claim_template: str) -> Optional[str]:
Yes -- I was wondering if we would need to move past the templates at some point.

2021-11-03 13:30 UTC, joecummings commented on cdse_covid/semantic_extraction/amr_extraction_utils.py
> +def identify_x_variable(amr: AMR, alignments: List[AMR_Alignment], claim_template: str) -> Optional[str]:
Documented in #22

2021-11-03 13:34 UTC, joecummings commented
Looks good. Only one nit and then can you rebase on master?

2021-11-03 16:07 UTC, merged