Add general method for finding select x-variables
joecummings/cdse-covid pull request #23
Opened 2021-11-03 17:52 UTC by elizlee

Closes #22 
WIP

2021-11-03 17:53 UTC, elizlee commented
With just the three rules there so far, it already seems to do pretty well when paired with the SRL.

2021-11-04 18:05 UTC, joecummings requested changes
I think this needs to be rebased

2021-11-04 19:17 UTC, joecummings commented on cdse_covid/semantic_extraction/run_amr_parsing.py
> +        # possible_x_variable = identify_x_variable(
Can we have this passed in as a param? That way we don't have to leave in some commented out code.

2021-11-04 19:18 UTC, elizlee commented on cdse_covid/semantic_extraction/run_amr_parsing.py
> +        # possible_x_variable = identify_x_variable(
Absolutely

2021-11-04 19:42 UTC, joecummings approved these changes
LGTM

2021-11-04 19:43 UTC, merged