Create E2E Pegasus Pipeline
joecummings/cdse-covid pull request #3
Opened 2021-10-12 20:01 UTC by joecummings

Big PR creating a Pegasus Pipelilne

This pegasus pipeline does the following:
```
preprocessing ------ claim_detection ------- srl_processing ------wikidata ------ unify
                                \______________ amr_parsing ________/ 
```

Currently, the output from unify looks like:
```
{
   "text": str,
   "template": str,
   "doc": str,
   "qnodes": List of interesting qnodes (Claimers and args)
}
```

2021-10-13 17:56 UTC, joecummings commented on setup.py
> +    python_requires=">=3.7",
Comment is old, but you are correct.

2021-10-13 18:02 UTC, joecummings commented on setup.sh
> +python -m spacy download en_core_web_sm
Hmm, that is true. I will look into why that is necessary.

2021-10-13 21:58 UTC, elizlee requested changes
Just a couple small changes, the rest looks good!

2021-10-13 21:58 UTC, elizlee commented on wikidata_linker/wikidata_linking.py
> +        f.write("\n")
Need to change `f` --> `file`

2021-10-13 21:58 UTC, elizlee commented on cdse_covid/pegasus_pipeline/claim_pipeline.py
> +    )
Add 8G resource_request

2021-10-14 00:02 UTC, elizlee commented on requirements.txt
> +vista_pegasus_wrapper
The package name is `pegasus-wrapper`

2021-10-14 00:08 UTC, merged