add checks
joecummings/cdse-covid pull request #33
Opened 2021-11-12 23:16 UTC by joecummings

- Add Makefile and linting checks
- Satisfy black, flake8, and pylint
- Satisfy PyDocStyle

2021-11-13 00:57 UTC, elizlee requested changes
One question + a few other things:
* It looks like the CI tools need to be added to the `requirements`
* Adding `make` instructions to the README might be useful

2021-11-13 00:57 UTC, elizlee commented on cdse_covid/pegasus_pipeline/run_amr_parsing_all.py
> +    """If a sentence exceeds the token limit, split the sentence into clauses \
This seems like a weird docstring format. Is the linter really asking for this?

2021-11-15 13:30 UTC, joecummings commented on cdse_covid/pegasus_pipeline/run_amr_parsing_all.py
> +    """If a sentence exceeds the token limit, split the sentence into clauses \
I have thoughts on this, as well. PyDocStyle always wants some sort of punctuation to end the first line (idk why), so you either have to force the sentence to take a shorter form or indicate that the line is still continuing. 

I agree, though, it looks weird.

2021-11-15 15:46 UTC, elizlee approved these changes
Thanks for adding this~
If you want to do something about the PyDocStyle format thing, I don't see harm in adding the configuration `--ignore=D400`

2021-11-15 15:48 UTC, merged