25 amr to qnode v2
joecummings/cdse-covid pull request #38
Opened 2021-11-15 21:24 UTC by joecummings

- Add resource files for DWD overlay mapping
- Add stub sentence-transformer to avoid execution stopping
- Add ClaimSemantics entity
- Add overlay job to Pegasus pipeline
- Fix import bug
- Remove claim semantic work from other files
- Add DWD overlay functionality and job
- Add python overlay file to params

2021-11-15 23:28 UTC, elizlee requested changes
A few questions/nits

2021-11-15 23:28 UTC, elizlee commented on wikidata_linker/disambiguate_with_amr_v2.py
> +        }
Was there a reason you didn't fetch the argument data from the "master" table like you did for the overlay?

2021-11-15 23:28 UTC, elizlee commented on wikidata_linker/disambiguate_with_amr_v2.py
> +    "ARG0-of": "A0",
Perhaps write an issue for this

2021-11-16 14:28 UTC, joecummings commented on cdse_covid/semantic_extraction/models/srl.py
> +    logging.warning("Cannot load AllenNLP models from this env.")
This is a bit of a hack so that `transition-amr-parser` conda env can load `SRLOutput`. Another way to go about this would be to create a separate file for the output format classes.

2021-11-16 14:28 UTC, joecummings commented on wikidata_linker/wikidata_linking.py
> +    logging.warning("Cannot load sentence transformers in this env.")
See answer above.

2021-11-16 14:29 UTC, joecummings commented on wikidata_linker/disambiguate_with_amr_v2.py
> +    arg_parser.add_argument("--amr-graphs", type=str, help="Sentence to get qnodes for")
I might honestly remove this part entirely. We are not currently calling this script directly.

2021-11-16 14:32 UTC, joecummings commented on wikidata_linker/disambiguate_with_amr_v2.py
> +        }
I don't think I wrote this code - I thought you did?

2021-11-16 14:41 UTC, joecummings commented on wikidata_linker/disambiguate_with_amr_v2.py
> +    "ARG0-of": "A0",
https://github.com/joecummings/cdse-covid/issues/39

2021-11-16 14:54 UTC, elizlee commented on wikidata_linker/disambiguate_with_amr_v2.py
> +        }
I thought you added the code to pull the argument data in `generate_overlay_dict` (lines ~333-343)

2021-11-16 16:24 UTC, joecummings commented on cdse_covid/semantic_extraction/models/srl.py
> +    logging.warning("Cannot load AllenNLP models from this env.")
Thoughts on this? @elizlee Do you have a preference on approaches?

2021-11-16 17:25 UTC, elizlee approved these changes
Looks good, thanks!

2021-11-16 17:28 UTC, elizlee commented on cdse_covid/semantic_extraction/models/srl.py
> +    logging.warning("Cannot load AllenNLP models from this env.")
I'd say this is fine for now, and I see you've created an issue for possibly replacing the hack

2021-11-16 17:51 UTC, merged